services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/src:/src                  
      - ${ADBREW_CODEBASE_PATH}/../test/data/tmp:/tmp     
    environment:
      - ENV_TYPE=staging
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/src:/src                  

  mongo:
    build: .
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/../test/data/db:/data/db   
    command: /usr/bin/mongod --bind_ip 0.0.0.0